### ISSUE TITLE
How to open RSS function?

### ISSUE THREAD

**Issue by younglaker** [ppoffice/hexo-theme-minos#10]
I haved installed `hexo-migrator-rss`, added `plugins: - hexo-generator-feed` to `_config.yml`  and excuted `hexo g`, but there doesn't have `atom.xml` .

**Comment by ppoffice** [comment]
I think you should install [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed), not hexo-migrator-rss.

**Comment by younglaker** [comment]
THX, My fault. I tried different tutorials and mixed up.

**Comment by younglaker** [comment]
I find `atom.xml`, but I find nothing in the web page.

in `_config.yml`:

    plugins:  
      - hexo-generator-feed

    rss: true

Right?

**Comment by ppoffice** [comment]
In the theme configuration:
```
# Header
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
  RSS: atom.xml                      <<<<<<<<<<<<<<<<<<<<<<<<<<<
```
