### ISSUE TITLE
show info. on  every page with google-analytics data

### ISSUE THREAD

**Issue by Papageno2** [ppoffice/hexo-theme-minos#117]
thx for this nice theme. 
Actually I know almost nothing about HTML and .js.

the question is how to show the tag on every page with google analytics data, like the `comment` tag on pages.

I have enabled the plugins
```yaml
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics: 
    tracking_id: G-G.......
```

**Comment by ppoffice** [comment]
Just remove google tracking ID from your config file.

**Comment by Papageno2** [comment]
> Just remove google tracking ID from your config file.

it seems unreasonable ? 
why removing tracking ID will add google-analytics data on my page footer ?
like this?

```yaml
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics: 
    tracking_id: 
```

actually it doesn't work.
