### ISSUE TITLE
About configuring Valine Comment document Errors

### ISSUE THREAD

**Issue by EIVX** [ppoffice/hexo-theme-minos#57]
There is an error in configuring Valine Comment service documentation in MINOS

Source Document

```
comment:
    type: valine
    app_id: xxxxxxxx        # (required) LeanCloud application id
    app_key: xxxxxxxx       # (required) LeanCloud application key
    notify: false           # (optional) receive email notification
    verify: false           # (optional) show verification code
    placeholder: xxxxxxxx   # (optional) comment box placeholder text
```
In fact, this will show the AppID and Appkey in the comments area of Minos
This should be the correct configuration 
```
comment:
    type: valine
    appId: xxxxxxxx        # (required) LeanCloud application id
    appKey: xxxxxxxx       # (required) LeanCloud application key
    notify: false           # (optional) receive email notification
    verify: false           # (optional) show verification code
    placeholder: xxxxxxxx   # (optional) comment box placeholder text
```
Thank you for your work.
