### ISSUE TITLE
mathjax怎么在指定页面打开，而不是每个页面都加载插件

### ISSUE THREAD

**Issue by acodercat** [ppoffice/hexo-theme-minos#81]
如题

**Comment by ppoffice** [comment]
@acodercat 主题配置文件设置为
```
plugins:
    mathjax: false
```

然后在需要的页面markdown头部加入
```yaml
plugins:
    ... (其他plugin的设置也一起copy过来)
    mathjax: true
```
